[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
size = 12.0

[colors.primary]
background = "#0D1014"
foreground = "#BDBDBD"

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.offset]
y = 2
